services:
  db:
    image: postgres
    restart: always
    container_name: db-apadrinhamento
    environment:
      POSTGRES_PASSWORD: senha
    volumes:
      - db-data:/var/lib/postgresql/data 
    ports:
      - 5432:5432
 
  adminer:
    image: adminer
    container_name: adminer-apadrinhamento
    restart: always
    ports:
      - 8080:8080

  server:
    build: .
    container_name: server-apadrinhamento
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:senha@db:5432/padrinho
    restart: always
    ports:
      - "${API_PORT:-3000}:3000"
    depends_on:
      - db

volumes:
  db-data: